<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>7</version>
    </parent>

    <groupId>io.trino.hadoop</groupId>
    <artifactId>hadoop-apache</artifactId>
    <version>3.2.0-17-HOPSFS</version>

    <name>hadoop-apache</name>
    <description>Shaded version of Apache Hadoop for Trino</description>
    <url>https://github.com/trinodb/trino-hadoop-apache</url>

    <inceptionYear>2013</inceptionYear>

    <licenses>
        <license>
            <name>Apache License 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <!-- see original projects for developer information -->
    </developers>

    <scm>
        <connection>scm:git:git://github.com/trinodb/trino-hadoop-apache.git</connection>
        <developerConnection>scm:git:git://github.com/trinodb/trino-hadoop-apache.git</developerConnection>
        <url>https://github.com/trinodb/trino-hadoop-apache</url>
        <tag>HEAD</tag>
    </scm>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.targetJdk>21</project.build.targetJdk>
        <shadeBase>io.trino.hadoop.\$internal</shadeBase>
        <dep.slf4j.version>1.7.36</dep.slf4j.version>
        <dep.hadoop.version>3.2.0.17-EE-RC1</dep.hadoop.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.hops</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>${dep.hadoop.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.hops</groupId>
                    <artifactId>hadoop-mapreduce-client-app</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.hops</groupId>
                    <artifactId>hadoop-mapreduce-client-jobclient</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.hops</groupId>
                    <artifactId>hadoop-yarn-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.hops</groupId>
                    <artifactId>hadoop-yarn-common</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.zookeeper</groupId>
                    <artifactId>zookeeper</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.curator</groupId>
                    <artifactId>curator-framework</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.curator</groupId>
                    <artifactId>curator-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.curator</groupId>
                    <artifactId>curator-recipes</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.directory.server</groupId>
                    <artifactId>apacheds-kerberos-codec</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-math</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-math3</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-beanutils</groupId>
                    <artifactId>commons-beanutils</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-beanutils</groupId>
                    <artifactId>commons-beanutils-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-digester</groupId>
                    <artifactId>commons-digester</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-el</groupId>
                    <artifactId>commons-el</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.jersey</groupId>
                    <artifactId>jersey-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.jersey</groupId>
                    <artifactId>jersey-server</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.jersey</groupId>
                    <artifactId>jersey-json</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.jersey</groupId>
                    <artifactId>jersey-servlet</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.github.pjfanning</groupId>
                    <artifactId>jersey-json</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>javax.servlet-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.servlet.jsp</groupId>
                    <artifactId>jsp-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-server</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-servlet</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-util</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-webapp</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.jcraft</groupId>
                    <artifactId>jsch</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>dnsjava</groupId>
                    <artifactId>dnsjava</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.minidev</groupId>
                    <artifactId>json-smart</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.nimbusds</groupId>
                    <artifactId>nimbus-jose-jwt</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.thoughtworks.paranamer</groupId>
                    <artifactId>paranamer</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-reload4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.reload4j</groupId>
                    <artifactId>reload4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>io.hops</groupId>
            <artifactId>hadoop-hdfs</artifactId>
            <version>${dep.hadoop.version}</version>
            <!-- <scope>runtime</scope> -->
            <exclusions>
                <exclusion>
                    <groupId>commons-codec</groupId>
                    <artifactId>commons-codec</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-daemon</groupId>
                    <artifactId>commons-daemon</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-el</groupId>
                    <artifactId>commons-el</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.fusesource.leveldbjni</groupId>
                    <artifactId>leveldbjni-all</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.jersey</groupId>
                    <artifactId>jersey-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.jersey</groupId>
                    <artifactId>jersey-server</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>javax.servlet-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-util-ajax</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-server</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-util</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>io.hops</groupId>
            <artifactId>hadoop-mapreduce-client-core</artifactId>
            <version>${dep.hadoop.version}</version>
            <scope>runtime</scope>
            <exclusions>
                <exclusion>
                    <groupId>io.hops</groupId>
                    <artifactId>hadoop-yarn-common</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.hops</groupId>
                    <artifactId>hadoop-yarn-client</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.inject.extensions</groupId>
                    <artifactId>guice-servlet</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-reload4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>io.hops</groupId>
            <artifactId>hadoop-azure</artifactId>
            <version>${dep.hadoop.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.wildfly.openssl</groupId>
                    <artifactId>wildfly-openssl</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>io.hops</groupId>
            <artifactId>hadoop-azure-datalake</artifactId>
            <version>${dep.hadoop.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.wildfly.openssl</groupId>
                    <artifactId>wildfly-openssl</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.lz4</groupId>
            <artifactId>lz4-java</artifactId>
            <version>1.8.0</version>
        </dependency>

        <!-- discard all logging from Hadoop -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
            <version>${dep.slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
            <version>${dep.slf4j.version}</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${dep.slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>${dep.slf4j.version}</version>
            <scope>runtime</scope>
        </dependency>

        <!-- for testing -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.2.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.0.0-M2</version>
                <executions>
                    <execution>
                        <id>default</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <rules>
                        <requireUpperBoundDeps />
                        <banDuplicatePomDependencyVersions />
                        <requireMavenVersion>
                            <version>3.5.0</version>
                        </requireMavenVersion>
                        <requireJavaVersion>
                            <version>${project.build.targetJdk}</version>
                        </requireJavaVersion>
                    </rules>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>${project.build.targetJdk}</source>
                    <target>${project.build.targetJdk}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M3</version>
                <configuration>
                    <trimStackTrace>false</trimStackTrace>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.0.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <source>${project.build.targetJdk}</source>
                    <quiet>true</quiet>
                    <doclint>-missing</doclint>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.6</version>
                <configuration>
                    <useAgent>true</useAgent>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <!-- Skip sources JAR for faster builds -->
                            <createSourcesJar>false</createSourcesJar>
                            <shadeSourcesContent>false</shadeSourcesContent>
                            <dependencyReducedPomLocation>${project.build.directory}/pom.xml</dependencyReducedPomLocation>
                            <promoteTransitiveDependencies>true</promoteTransitiveDependencies>
                            <artifactSet>
                                <excludes>
                                    <exclude>com.google.errorprone:error_prone_annotations</exclude>
                                    <exclude>com.google.guava:failureaccess</exclude>
                                    <exclude>com.google.guava:guava</exclude>
                                    <exclude>com.google.j2objc:j2objc-annotations</exclude>
                                    <exclude>org.checkerframework:checker-qual</exclude>
                                    <exclude>org.xerial.snappy:snappy-java</exclude>
                                    <exclude>org.lz4:lz4-java</exclude>
                                    <exclude>com.squareup.okhttp3:okhttp</exclude>
                                    <exclude>com.squareup.okio:okio</exclude>
                                    <exclude>org.jetbrains.kotlin:kotlin-stdlib</exclude>
                                    <exclude>org.jetbrains.kotlin:kotlin-stdlib-common</exclude>
                                </excludes>
                            </artifactSet>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                            </transformers>
                            <relocations>
                                <!-- Shade all packages except org.apache.hadoop and io.hops -->
                                <!-- Main package patterns -->
                                <relocation>
                                    <pattern>com.</pattern>
                                    <shadedPattern>${shadeBase}.com.</shadedPattern>
                                    <excludes>
                                        <exclude>com.sun.security.**</exclude>
                                        <exclude>com.sun.management.**</exclude>
                                        <exclude>com.ibm.security.**</exclude>
                                    </excludes>
                                </relocation>
                                <relocation>
                                    <pattern>org.</pattern>
                                    <shadedPattern>${shadeBase}.org.</shadedPattern>
                                    <excludes>
                                        <exclude>org.apache.hadoop.**</exclude>
                                    </excludes>
                                </relocation>
                                <relocation>
                                    <pattern>net.</pattern>
                                    <shadedPattern>${shadeBase}.net.</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.</pattern>
                                    <shadedPattern>${shadeBase}.io.</shadedPattern>
                                    <excludes>
                                        <exclude>io.hops.**</exclude>
                                        <exclude>io.trino.**</exclude>
                                    </excludes>
                                </relocation>
                                
                                
                                <!-- jakarta packages -->
                                <relocation>
                                    <pattern>jakarta.</pattern>
                                    <shadedPattern>${shadeBase}.jakarta.</shadedPattern>
                                </relocation>
                                
                                <!-- Other common root packages -->
                                <relocation>
                                    <pattern>ch.qos.</pattern>
                                    <shadedPattern>${shadeBase}.ch.qos.</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>it.unimi.</pattern>
                                    <shadedPattern>${shadeBase}.it.unimi.</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>dk.brics.</pattern>
                                    <shadedPattern>${shadeBase}.dk.brics.</shadedPattern>
                                </relocation>
                                
                                <!-- Mozilla pattern from original config -->
                                <relocation>
                                    <pattern>mozilla</pattern>
                                    <shadedPattern>${shadeBase}.mozilla</shadedPattern>
                                </relocation>
                                
                                <!-- Root-level packages -->
                                <relocation>
                                    <pattern>reactor.</pattern>
                                    <shadedPattern>${shadeBase}.reactor.</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>google.</pattern>
                                    <shadedPattern>${shadeBase}.google.</shadedPattern>
                                </relocation>
                            </relocations>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/maven/**</exclude>
                                        <exclude>META-INF/versions/**</exclude>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                        <exclude>module-info.java</exclude>
                                        <!-- Exclude Log4j resources to prevent conflicts -->
                                        <exclude>Log4j-charsets.properties</exclude>
                                        <exclude>Log4j-config.xsd</exclude>
                                        <exclude>Log4j-events.dtd</exclude>
                                        <exclude>Log4j-events.xsd</exclude>
                                        <exclude>Log4j-levels.xsd</exclude>
                                        <exclude>Log4j2Plugins.dat</exclude>
                                        <exclude>META-INF/log4j-provider.properties</exclude>
                                        <!-- Exclude JUnit resources and classes -->
                                        <exclude>junit/**</exclude>
                                        <exclude>org/junit/**</exclude>
                                        <!-- Exclude test-related resources -->
                                        <exclude>assets/org/apache/commons/math3/exception/util/LocalizedFormats_*.properties</exclude>
                                        <!-- Exclude cloud provider resource conflicts -->
                                        <exclude>mime.types</exclude>
                                        <exclude>dependencies.properties</exclude>
                                        <exclude>azure-core.properties</exclude>
                                        <exclude>azure-storage-blob.properties</exclude>
                                        <!-- Exclude all javax classes to prevent conflicts -->
                                        <exclude>javax/**</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>org.slf4j:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/services/**</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>com.fasterxml.jackson.*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/services/**</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>com.fasterxml.woodstox:woodstox-core</artifact>
                                    <excludes>
                                        <exclude>META-INF/services/**</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>jakarta.activation:jakarta.activation-api</artifact>
                                    <excludes>
                                        <exclude>pom.xml</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>org.apache.commons:commons-configuration2</artifact>
                                    <excludes>
                                        <exclude>*.dtd</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>org.eclipse.jetty:jetty-util</artifact>
                                    <excludes>
                                        <exclude>about.html</exclude>
                                        <exclude>jetty-dir.css</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>org.eclipse.jetty:jetty-util-ajax</artifact>
                                    <excludes>
                                        <exclude>about.html</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>org.apache.kerby:kerb-simplekdc</artifact>
                                    <excludes>
                                        <exclude>krb5-template.conf</exclude>
                                        <exclude>krb5_udp-template.conf</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>org.apache.kerby:kerb-util</artifact>
                                    <excludes>
                                        <exclude>ccache.txt</exclude>
                                        <exclude>keytab.txt</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>com.microsoft.azure:azure-data-lake-store-sdk</artifact>
                                    <excludes>
                                        <exclude>com/microsoft/azure/datalake/store/HttpTransport.class</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>io.hops:hadoop-common</artifact>
                                    <excludes>
                                        <exclude>*.h</exclude>
                                        <exclude>org/apache/hadoop/fs/FileSystem.class</exclude>
                                        <exclude>org/apache/hadoop/fs/FileSystem$*.class</exclude>
                                        <exclude>org/apache/hadoop/util/NativeCodeLoader.class</exclude>
                                        <exclude>org/apache/hadoop/security/UserGroupInformation.class</exclude>
                                        <exclude>org/apache/hadoop/security/UserGroupInformation$*.class</exclude>
                                        <exclude>org/apache/hadoop/crypto/key/kms/KMSClientProvider.class</exclude>
                                        <exclude>org/apache/hadoop/crypto/key/kms/KMSClientProvider$*.class</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>io.hops:hadoop-mapreduce-client-core</artifact>
                                    <excludes>
                                        <exclude>mapred-default.xml.orig</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>${project.groupId}:${project.artifactId}</artifact>
                                    <includes>
                                        <include>**</include>
                                    </includes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.0.0-M1</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>2.5.3</version>
                    <configuration>
                        <mavenExecutorId>forked-path</mavenExecutorId>
                        <pushChanges>false</pushChanges>
                        <localCheckout>true</localCheckout>
                        <useReleaseProfile>false</useReleaseProfile>
                        <preparationGoals>clean install</preparationGoals>
                        <autoVersionSubmodules>true</autoVersionSubmodules>
                        <tagNameFormat>@{project.version}</tagNameFormat>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
    <dependencyManagement>
        <dependencies>
            <!-- Resolve version conflicts reported by enforcer -->
            <dependency>
                <groupId>com.google.code.findbugs</groupId>
                <artifactId>jsr305</artifactId>
                <version>3.0.2</version>
            </dependency>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>2.11.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.12.0</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.12.7</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <repositories>
      <repository>
        <id>HopsEE</id>
        <name>Hops Release Repository</name>
        <url>https://nexus.hops.works/repository/hops-artifacts</url>
        <releases>
          <enabled>true</enabled>
        </releases>
        <snapshots>
          <enabled>true</enabled>
          <updatePolicy>interval:15</updatePolicy>
        </snapshots>
      </repository>
    </repositories>
</project>
